/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jpanels;

/**
 *
 * @author edenj
 */
public class JPanelMain extends javax.swing.JPanel {

    private javax.swing.JFrame window = null;
    private jpanels.JPanelDashBoard jPanelDefault;
    private javax.swing.JPanel jPanelSignatures;
    private jpanels.JPanelDiaries jPanelDiary;

    /**
     * Creates new form JPanelMain
     *
     * @param window
     */
    public JPanelMain(javax.swing.JFrame window) {
        this.window = window;
        initComponents();
        moreConfiguration();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDashBoard = new javax.swing.JPanel();
        jPanelMenuDashBoard = new javax.swing.JPanel();
        jLabelIconMenuDashBoard = new javax.swing.JLabel();
        jLabelMenuDashBoard = new javax.swing.JLabel();
        jPanelMenuDiary = new javax.swing.JPanel();
        jLabelIconMenuDiary = new javax.swing.JLabel();
        jLabelMenuDiary = new javax.swing.JLabel();
        jPanelMenuGenerate = new javax.swing.JPanel();
        jLabelIconMenuGenerate = new javax.swing.JLabel();
        jLabelMenuGenerate = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanelProfile = new javax.swing.JPanel();
        jLabelIconLogo = new javax.swing.JLabel();
        jPanelInicio = new javax.swing.JPanel();
        jLabelAuthorMain = new javax.swing.JLabel();
        jLabelDefault = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenuDashBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenuDashBoardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenuDashBoardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMenuDashBoardMouseExited(evt);
            }
        });

        jLabelIconMenuDashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menuIcon.png"))); // NOI18N

        jLabelMenuDashBoard.setText("Horarios");

        javax.swing.GroupLayout jPanelMenuDashBoardLayout = new javax.swing.GroupLayout(jPanelMenuDashBoard);
        jPanelMenuDashBoard.setLayout(jPanelMenuDashBoardLayout);
        jPanelMenuDashBoardLayout.setHorizontalGroup(
            jPanelMenuDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuDashBoardLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelIconMenuDashBoard)
                .addGap(15, 15, 15)
                .addComponent(jLabelMenuDashBoard)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanelMenuDashBoardLayout.setVerticalGroup(
            jPanelMenuDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuDashBoardLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelMenuDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMenuDashBoard)
                    .addComponent(jLabelIconMenuDashBoard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMenuDiary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenuDiaryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenuDiaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMenuDiaryMouseExited(evt);
            }
        });

        jLabelIconMenuDiary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/subjectsIcon.png"))); // NOI18N

        jLabelMenuDiary.setText("Asignaturas");

        javax.swing.GroupLayout jPanelMenuDiaryLayout = new javax.swing.GroupLayout(jPanelMenuDiary);
        jPanelMenuDiary.setLayout(jPanelMenuDiaryLayout);
        jPanelMenuDiaryLayout.setHorizontalGroup(
            jPanelMenuDiaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuDiaryLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelIconMenuDiary)
                .addGap(15, 15, 15)
                .addComponent(jLabelMenuDiary)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelMenuDiaryLayout.setVerticalGroup(
            jPanelMenuDiaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuDiaryLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelMenuDiaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMenuDiary)
                    .addComponent(jLabelIconMenuDiary))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMenuGenerate.setPreferredSize(new java.awt.Dimension(102, 40));
        jPanelMenuGenerate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenuGenerateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenuGenerateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMenuGenerateMouseExited(evt);
            }
        });
        jPanelMenuGenerate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconMenuGenerate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/diaryIcon.png"))); // NOI18N
        jPanelMenuGenerate.add(jLabelIconMenuGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelMenuGenerate.setText("Generar");
        jPanelMenuGenerate.add(jLabelMenuGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        javax.swing.GroupLayout jPanelDashBoardLayout = new javax.swing.GroupLayout(jPanelDashBoard);
        jPanelDashBoard.setLayout(jPanelDashBoardLayout);
        jPanelDashBoardLayout.setHorizontalGroup(
            jPanelDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenuDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMenuDiary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMenuGenerate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanelDashBoardLayout.setVerticalGroup(
            jPanelDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashBoardLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanelMenuDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanelMenuDiary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanelMenuGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        add(jPanelDashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 350));

        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Bienvenido");

        jLabelAuthor.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelAuthor.setText("|   BY JD");

        jSpinner1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jSpinner1.setToolTipText("Semestre por Default");
        jSpinner1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Semestre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 12))); // NOI18N
        jSpinner1.setFocusable(false);
        jSpinner1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 600, 50));

        jLabelIconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanelProfileLayout = new javax.swing.GroupLayout(jPanelProfile);
        jPanelProfile.setLayout(jPanelProfileLayout);
        jPanelProfileLayout.setHorizontalGroup(
            jPanelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfileLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelIconLogo)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelProfileLayout.setVerticalGroup(
            jPanelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProfileLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabelIconLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        add(jPanelProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        jLabelAuthorMain.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelAuthorMain.setText("By Jair Diaz");

        jLabelDefault.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabelDefault.setText("Generador de Horarios");

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                        .addComponent(jLabelAuthorMain)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                        .addComponent(jLabelDefault)
                        .addGap(90, 90, 90))))
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabelDefault)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(jLabelAuthorMain)
                .addGap(23, 23, 23))
        );

        add(jPanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 600, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelMenuDashBoardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuDashBoardMouseEntered
        this.jPanelMenuDashBoard.setBackground(tools.RootVariables.backgroundDashBoardMenuHover);
        this.jPanelMenuDashBoard.setBorder(tools.RootVariables.borderMain);
    }//GEN-LAST:event_jPanelMenuDashBoardMouseEntered

    private void jPanelMenuDiaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuDiaryMouseEntered
        this.jPanelMenuDiary.setBackground(tools.RootVariables.backgroundDashBoardMenuHover);
        this.jPanelMenuDiary.setBorder(tools.RootVariables.borderMain);
    }//GEN-LAST:event_jPanelMenuDiaryMouseEntered

    private void jPanelMenuDashBoardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuDashBoardMouseExited
        this.jPanelMenuDashBoard.setBackground(tools.RootVariables.backgroundDashBoard);
        this.jPanelMenuDashBoard.setBorder(null);
    }//GEN-LAST:event_jPanelMenuDashBoardMouseExited

    private void jPanelMenuDiaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuDiaryMouseExited
        this.jPanelMenuDiary.setBackground(tools.RootVariables.backgroundDashBoard);
        this.jPanelMenuDiary.setBorder(null);
    }//GEN-LAST:event_jPanelMenuDiaryMouseExited

    private void jPanelMenuDashBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuDashBoardMouseClicked
        this.remove(this.jPanelInicio);
        if (this.jPanelDefault == null) {
            this.jPanelDefault = new JPanelDashBoard(this.window);
        } else {
            this.jPanelDefault.refreshComboBox();
        }
        tools.Interfaz.changePanel(window, jPanelDefault, tools.RootVariables.borderMain, "Horarios", jLabelTitle, 150, 50, 600, 450);
        this.jPanelInicio = this.jPanelDefault;
    }//GEN-LAST:event_jPanelMenuDashBoardMouseClicked

    private void jPanelMenuDiaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuDiaryMouseClicked
        this.remove(this.jPanelInicio);
        if (this.jPanelSignatures == null) {
            this.jPanelSignatures = new JPanelSubjects(this.window, this.jSpinner1);
        }
        tools.Interfaz.changePanel(window, jPanelSignatures, tools.RootVariables.borderMain, "Asignaturas", jLabelTitle, 150, 50, 600, 450);
        this.jPanelInicio = this.jPanelSignatures;
    }//GEN-LAST:event_jPanelMenuDiaryMouseClicked

    private void jPanelMenuGenerateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuGenerateMouseClicked
        this.remove(this.jPanelInicio);
        if (this.jPanelDiary == null) {
            this.jPanelDiary = new JPanelDiaries();
        }

        java.util.ArrayList<java.util.ArrayList<listas.Nodo>> horarios = tools.Diary.combinarHorarios();
        this.jPanelDiary.refreshData(horarios);

        tools.Interfaz.changePanel(window, jPanelDiary, tools.RootVariables.borderMain, "Asignaturas", jLabelTitle, 150, 50, 600, 450);
        this.jPanelInicio = this.jPanelDiary;

    }//GEN-LAST:event_jPanelMenuGenerateMouseClicked

    private void jPanelMenuGenerateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuGenerateMouseEntered
        this.jPanelMenuGenerate.setBackground(tools.RootVariables.backgroundDashBoardMenuHover);
        this.jPanelMenuGenerate.setBorder(tools.RootVariables.borderMain);
    }//GEN-LAST:event_jPanelMenuGenerateMouseEntered

    private void jPanelMenuGenerateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuGenerateMouseExited
        this.jPanelMenuGenerate.setBackground(tools.RootVariables.backgroundDashBoard);
        this.jPanelMenuGenerate.setBorder(null);
    }//GEN-LAST:event_jPanelMenuGenerateMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelAuthorMain;
    private javax.swing.JLabel jLabelDefault;
    private javax.swing.JLabel jLabelIconLogo;
    private javax.swing.JLabel jLabelIconMenuDashBoard;
    private javax.swing.JLabel jLabelIconMenuDiary;
    private javax.swing.JLabel jLabelIconMenuGenerate;
    private javax.swing.JLabel jLabelMenuDashBoard;
    private javax.swing.JLabel jLabelMenuDiary;
    private javax.swing.JLabel jLabelMenuGenerate;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelDashBoard;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelMenuDashBoard;
    private javax.swing.JPanel jPanelMenuDiary;
    private javax.swing.JPanel jPanelMenuGenerate;
    private javax.swing.JPanel jPanelProfile;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
    /**
     * Método que nos permite configurar más cosas del JPanel despues de
     * inicializar los elementos de este.
     */
    private void moreConfiguration() {
        //Set Backgrounds JPanels
        this.jPanelDashBoard.setBackground(tools.RootVariables.backgroundDashBoard);

        this.jPanelMenuDashBoard.setBackground(tools.RootVariables.backgroundDashBoard);
        this.jPanelMenuDiary.setBackground(tools.RootVariables.backgroundDashBoard);
        this.jPanelMenuGenerate.setBackground(tools.RootVariables.backgroundDashBoard);

        this.jPanelHeader.setBackground(tools.RootVariables.backgroundHeader);
        this.jPanelProfile.setBackground(tools.RootVariables.backgroundProfile);

        this.jPanelInicio.setBackground(tools.RootVariables.backgroundDefault);

        //Set Foregrounds
        this.jLabelMenuDashBoard.setForeground(tools.RootVariables.backgroundDefault);
        this.jLabelMenuDiary.setForeground(tools.RootVariables.backgroundDefault);
        this.jLabelMenuGenerate.setForeground(tools.RootVariables.backgroundDefault);

        this.jLabelTitle.setForeground(tools.RootVariables.backgroundDefault);
        this.jLabelAuthor.setForeground(tools.RootVariables.backgroundDefault);

        //Set Fonts
        this.jLabelMenuDashBoard.setFont(tools.RootVariables.fontMenu);

        this.jLabelMenuDiary.setFont(tools.RootVariables.fontMenu);
        this.jLabelMenuGenerate.setFont(tools.RootVariables.fontMenu);
        this.jLabelTitle.setFont(tools.RootVariables.fontHeader);

        //Set Borders
        this.jPanelInicio.setBorder(tools.RootVariables.borderMain);

        ((javax.swing.JSpinner.DefaultEditor) this.jSpinner1.getEditor()).getTextField().setHorizontalAlignment(0);
    }
}
